/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BovinoController;
import controller.CompraController;
import controller.RacaController;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bovino;
import model.Compra;
import model.Raca;

/**
 *
 * @author Eduardo
 */
public class CadastroCompraView extends javax.swing.JInternalFrame {
    private int idUser;
    private int idBovino;
    private int idCompra;
    RacaController cr = new  RacaController();
    BovinoController bc = new  BovinoController();
    CompraController cc = new CompraController();
    Compra compra;
    Bovino bovino;
    
    List<Compra> recLista = null;
   
    public CadastroCompraView(int idUser) {
        initComponents();
        // comboRaca.setSelectedItem(cr.retornaRaca());
         setRaca(cr.getRaca());
         carregaLista(idUser);
       preencherTabela();
        setIdUser(idUser);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
    }

    public int getIdUser() {
        return idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public int getIdBovino() {
        return idBovino;
    }

    public void setIdBovino(int idBovino) {
        this.idBovino = idBovino;
    }

    public int getIdCompra() {
        return idCompra;
    }

    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }
    
    
    public void carregaLista(int idUser){
         recLista = cc.listar(idUser);
    }
     public void preencherTabela(){
        DefaultTableModel modelo = (DefaultTableModel)tbCompras.getModel();
        modelo.setNumRows(0);
        
        tbCompras.getColumnModel().getColumn(0).setPreferredWidth(2);
        tbCompras.getColumnModel().getColumn(1).setPreferredWidth(20);//largura das coluna
        tbCompras.getColumnModel().getColumn(2).setPreferredWidth(95);
        tbCompras.getColumnModel().getColumn(3).setPreferredWidth(10);
        
        
        for(int i=0; i<recLista.size(); i++){
         
            modelo.addRow(new Object[]{
             
             recLista.get(i).getId(),   
             recLista.get(i).getNome(),
             recLista.get(i).getEndereco(),
             recLista.get(i).getTelefone(),
             });
            
          
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtBrinco = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        comboRaca = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCompras = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtDataCompra = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Compra");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(" Registros de Compras ");

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor da compra: R$");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Endereço:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Peso atual: Kg");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Raça:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Brinco Nº");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Informaçõe do vendedor");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Informaçõe do bovino");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Data da compra:");

        btnExcluir.setBackground(new java.awt.Color(153, 0, 0));
        btnExcluir.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnExcluir.setText("Excluir Selecionada");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Data de nascimento:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("GERENCIADOR DE COMPRA E VENDA DE GADO");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("BovinoWare");

        jLabel15.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel15.setText("BW");

        tbCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Vendedor", "Endereço do Vendedor", "Telefone do Vendedor"
            }
        ));
        tbCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCompras);
        if (tbCompras.getColumnModel().getColumnCount() > 0) {
            tbCompras.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        btnSalvar.setBackground(new java.awt.Color(51, 204, 0));
        btnSalvar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnSalvar.setText("Cadastrar Nova");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(204, 204, 0));
        btnEditar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnEditar.setText("Editar Selecionada");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Cadastramento de Compra");

        try {
            txtDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEndereco))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtBrinco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(comboRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel14))
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnEditar)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(232, 232, 232)
                    .addComponent(jLabel16)
                    .addContainerGap(798, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtBrinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel16)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
     public boolean validaValor(){
    try{
        Double.parseDouble (txtValor.getText());
        return true;
    }catch (Exception e) {
      
       JOptionPane.showMessageDialog(null, "O campo valor pode registrar números inteiros ou cecimais com ( . ) ex: ' 500 ou 499.90'");
       return false;
       }                        
    }   
    public boolean validaPeso(){
        try {
        Integer.parseInt(txtPeso.getText());
        return true;
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "O campo peso pode registrar apenas números inteiros ex: ' 500 '");
        return false;
    }
                         
    }   
    public boolean validaData(){
    try{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");// validação
                    
        Date data1 = sdf.parse(txtDataNascimento.getText()); 
        Date data2 = sdf.parse(txtDataCompra.getText()); 
                    
        String dataNascimento = data1+"";
        String dataCompra = data2+"";
        return true;
    }catch (ParseException ex) {
       Logger.getLogger(CadastroCompraView.class.getName()).log(Level.SEVERE, null, ex);
       JOptionPane.showMessageDialog(null, "Erro nas datas! use o formato dd/mm/aaaa");
       return false;
       }                        
    }                        
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este registro de compra? O bovino tambem sera removido do rebanho!","Confirmação",JOptionPane.YES_NO_OPTION);
        if(resp==0){
            try {
                 bc.cancelarRegistroCompra(getIdBovino());
                
                 cc.excluir(getIdCompra());
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
            }
               
            
        }
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        carregaLista(getIdUser());
        preencherTabela();
        
    }//GEN-LAST:event_btnExcluirActionPerformed
 public void  preencherCampos(int idCompra){
        int idBovino = cc.buscaCompra(idCompra).getIdBovino();
        
        setIdBovino(idBovino);
       
        boolean vendido = bc.getBovino(idBovino, getIdUser()).isVendido();
        
        if(vendido == false){
         int idRaca = bc.getBovino(idBovino, getIdUser()).getIdRaca();
         String brinco = bc.getBovino(idBovino, getIdUser()).getBrinco();
         String dataNascimento = bc.getBovino(idBovino, getIdUser()).getDataNascimento();
         String dataCompra = bc.getBovino(idBovino, getIdUser()).getDataCompra();
         String pesoCompra = bc.getBovino(idBovino, getIdUser()).getPesoCompra()+"";
         String valorCompra = bc.getBovino(idBovino, getIdUser()).getValorCompra()+"";
        
         String nome = cc.buscaCompra(idCompra).getNome();
         String telefone =  cc.buscaCompra(idCompra).getTelefone();   
         String endereco =  cc.buscaCompra(idCompra).getEndereco(); 
         
       
        
         txtNome.setText(nome);
         txtEndereco.setText(endereco);
         txtTelefone.setText(telefone);
         txtDataCompra.setText(dataCompra);
         txtValor.setText(valorCompra);
         txtPeso.setText(pesoCompra);
         txtBrinco.setText(brinco);
         txtDataNascimento.setText(dataNascimento);
         comboRaca.setSelectedItem(cr.retornaRaca(idRaca));
        
        btnEditar.setVisible(true);
        btnExcluir.setVisible(true);
        }
        else{
         btnEditar.setVisible(false);
         btnExcluir.setVisible(false);
         int idRaca = bc.getBovino(idBovino, getIdUser()).getIdRaca();
         String brinco = bc.getBovino(idBovino, getIdUser()).getBrinco();
         String dataNascimento = bc.getBovino(idBovino, getIdUser()).getDataNascimento();
         String dataCompra = bc.getBovino(idBovino, getIdUser()).getDataCompra();
         String pesoCompra = bc.getBovino(idBovino, getIdUser()).getPesoCompra()+"";
         String valorCompra = bc.getBovino(idBovino, getIdUser()).getValorCompra()+"";
        
         String nome = cc.buscaCompra(idCompra).getNome();
         String telefone =  cc.buscaCompra(idCompra).getTelefone();   
         String endereco =  cc.buscaCompra(idCompra).getEndereco(); 
         
       
        
         txtNome.setText(nome);
         txtEndereco.setText(endereco);
         txtTelefone.setText(telefone);
         txtDataCompra.setText(dataCompra);
         txtValor.setText(valorCompra);
         txtPeso.setText(pesoCompra);
         txtBrinco.setText(brinco);
         txtDataNascimento.setText(dataNascimento);
         comboRaca.setSelectedItem(cr.retornaRaca(idRaca));
         
         JOptionPane.showMessageDialog(null, "Esse bovino já foi vendido!");
        }
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!txtNome.getText().isEmpty() && !txtEndereco.getText().isEmpty() && !txtTelefone.getText().isEmpty()){
            if(!txtDataCompra.getText().isEmpty() && !txtValor.getText().isEmpty() &&!txtDataNascimento.getText().isEmpty() && !txtPeso.getText().isEmpty()){
                
                boolean dataValida = validaData();
                boolean validaValor = validaValor();
                boolean validaPeso = validaPeso();
                
                if(dataValida == true && validaValor == true && validaPeso == true ){
                    
                    
                    
                    try{   
                    bovino = new Bovino();
                    bovino.setIdUser(idUser);
                    bovino.setIdRaca(cr.retornaId(comboRaca.getSelectedItem().toString()));
                    bovino.setBrinco(txtBrinco.getText());
                    bovino.setDataNascimento(txtDataNascimento.getText());
                    bovino.setDataCompra(txtDataCompra.getText());
                    bovino.setPesoCompra(parseInt (txtPeso.getText()));
                    bovino.setValorCompra(parseDouble (txtValor.getText()));
                    bovino.setRegistrado(false);
                    bovino.setVendido(false);
                    
                    bc.registraCompra(bovino);
                    
                    int idBovino = bc.buscaSemRegistro();
                   
                    compra = new Compra();
                    
                    compra.setIdUsuario(idUser);
                    compra.setIdBovino(idBovino);
                    compra.setNome(txtNome.getText());
                    compra.setTelefone(txtTelefone.getText());
                    compra.setEndereco(txtEndereco.getText());
                    
                    cc.salvar(compra);
                    
                    bc.vinculaBovino(idBovino);
                    
                    
                       txtBrinco.setText("");
                       txtDataNascimento.setText("");
                       txtPeso.setText("");
                       txtValor.setText("");
                     
                    
                    } catch(Error erro){
                         JOptionPane.showMessageDialog(null, "Preenxe os campos CORRETAMENTE! campo peso somente use numerosinteiros,");
                    } 
                    
                    
                }
                
            }
            else {JOptionPane.showMessageDialog(null, "Preencha TODOS os campos !");}   
            
        }
        else {JOptionPane.showMessageDialog(null, "Preencha TODOS os campos !");}
        carregaLista(getIdUser());
        preencherTabela();
         btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(!txtNome.getText().isEmpty() && !txtEndereco.getText().isEmpty() && !txtTelefone.getText().isEmpty()){
            if(!txtDataCompra.getText().isEmpty() && !txtValor.getText().isEmpty() &&!txtDataNascimento.getText().isEmpty() && !txtPeso.getText().isEmpty()){
                
                boolean dataValida = validaData();
                boolean validaValor = validaValor();
                boolean validaPeso = validaPeso();
                
                if(dataValida == true && validaValor == true && validaPeso == true ){
                    
                    
                    
                    try{   
                    bovino = new Bovino();
                
                    bovino.setIdRaca(cr.retornaId(comboRaca.getSelectedItem().toString()));
                    bovino.setBrinco(txtBrinco.getText());
                    bovino.setDataNascimento(txtDataNascimento.getText());
                    bovino.setDataCompra(txtDataCompra.getText());
                    bovino.setPesoCompra(parseInt (txtPeso.getText()));
                    bovino.setValorCompra(parseDouble (txtValor.getText()));
                    
                    
                    bc.editar(bovino, getIdBovino());
                    
                    
                   
                    compra = new Compra();
                    
                    compra.setIdUsuario(idUser);
                    compra.setIdBovino(idBovino);
                    compra.setNome(txtNome.getText());
                    compra.setTelefone(txtTelefone.getText());
                    compra.setEndereco(txtEndereco.getText());
                    
                    cc.editar(compra, getIdCompra());
                    
                   
                    
                    
                       txtBrinco.setText("");
                       txtDataNascimento.setText("");
                       txtPeso.setText("");
                       txtValor.setText("");
                     
                    
                    } catch(Error erro){
                         JOptionPane.showMessageDialog(null, "Preenxe os campos CORRETAMENTE! campo peso somente use numerosinteiros,");
                    } 
                    
                    
                }
                
            }
            else {JOptionPane.showMessageDialog(null, "Preencha TODOS os campos !");}   
            
        }
        else {JOptionPane.showMessageDialog(null, "Preencha TODOS os campos !");}
        carregaLista(getIdUser());
        preencherTabela();
         btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        
        
        carregaLista(getIdUser());
        preencherTabela();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tbComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbComprasMouseClicked
            int idC=0;
           
        if(evt.getClickCount() == 1){ 
            //capitura dados
            Object objID = (tbCompras.getValueAt(tbCompras.getSelectedRow(), 0));
                String id = objID.toString(); 
           
        idC = parseInt(id);   
        setIdCompra(idC);
        }     
        preencherCampos(idC);
    }//GEN-LAST:event_tbComprasMouseClicked

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed
 private void setRaca(List<String> marca){
        while(!marca.isEmpty()){
            comboRaca.addItem(marca.remove(0));   
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbCompras;
    private javax.swing.JTextField txtBrinco;
    private javax.swing.JFormattedTextField txtDataCompra;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
